Repository omg/vivi, pull requests merged in 2024-03, with the labels that each got.

#6 Fix Typo Words
  changes/Tellurate-2.diff
Labels: addition, removal

#7 Remove typo words
  changes/邵一.diff
Labels: removal

#8 Common words addition
  changes/邵二.diff
Labels: addition
